Certificate otp ui draft
NethServer/nethserver-vpn-ui pull request #24
Opened 2020-04-08 16:03 UTC by stephdl

2020-04-09 07:03 UTC, gsanchietti commented
> I display the checkbox
> 
> if the user has a vpn access
> if the vpn is enabled
> if the vpn is set to the mode certificate-otp

I think you already have all required info and a new flag is not needed.
Just checkout this PoC code (not optimized):
```perl
#!/usr/bin/perl

use JSON;
use esmith::ConfigDB;

my $user = $ARGV[0];

my $db = esmith::ConfigDB->open_ro();
my $status = $db->get_prop('openvpn@host-to-net','status') || 'disabled';
my $auth = $db->get_prop('openvpn@host-to-net','AuthMode') || 'password';

my $accounts = decode_json(`/usr/libexec/nethserver/api/nethserver-vpn-ui/openvpn-rw/list-accounts 2>/dev/null`);

foreach (@$accounts) {
    my $n = $_->{'name'};
    print "n=$n\n";
    if ($status eq 'enabled' && $auth eq 'certificate-otp' && $n eq $user) {
        print "2FA vpn $user ENABLED\n";
        exit;
    }
}
print "2FA vpn $user DISABLED\n";
```

You can invoke with:
```
./check.pl <username>
```

2020-04-09 17:30 UTC, stephdl commented
```
my $db = esmith::ConfigDB->open_ro();
my $status = $db->get_prop('openvpn@host-to-net','status') || 'disabled';
my $auth = $db->get_prop('openvpn@host-to-net','AuthMode') || 'password';
```

this needs sudo .... isn't it ?

````
Basically, you can add this code inside the /usr/libexec/nethserver/api/system-authorization/read API and you should be able to display (or not) the VPN checkbox.
```

we have no sudo in `/usr/libexec/nethserver/api/system-authorization/read` and if you add sudo in this API, everybody is seen like `root`


do I am wrong ?

however I think that my code must be pushed inside an action of nethserver-openvpn-save event, else when you modify something in NethGui we will have no change. For example if you change AuthMode from nethgui, I will see always my users granted to otp.

we can talk of it tomorrow, today I cannot connect.

2020-04-10 07:04 UTC, stephdl commented
yes tested, it confirmed the user `stephane` (no sudo, only shell access) cannot use the script, the settings page is under the privilege of the user.

```
[stephane@deomain.com@prometheus ~]$ /usr/libexec/nethserver/certificate-vpn-test
Can't call method "get_prop" on an undefined value at /usr/libexec/nethserver/certificate-vpn-test line 9.
```

2020-04-10 07:22 UTC, gsanchietti commented
You're right, you need to sudo to access the information.
I was pretty sure we already used an hacky sudo call somewhere inside the autorization API but I can't find it right now.

Still the current flag implementation is too complex.
What about a template that outputs the list of vpn users only if the certificate-otp  auth mode is enabled? You could expand the template inside `nethserver-vpn-save` event.
Then you can check with a simple grep from the authorization API.
This implementation could be simple

2020-04-10 07:25 UTC, stephdl commented
yes the code is complex.

I would like to minimize

an action triggered by nethserver-vpn-save and nethserver-openvpn-save, a bit like your code, if  I found the user, then I drop a file to `/var/lib/nethserver/openvpn-certificate-otp-username`

I think the code will be shorter , what do you think ?

2020-04-10 07:30 UTC, gsanchietti commented
Yes, it could be a good solution.
So, the actions must remove all files inside the directory than recreate only the one for existing users.

2020-04-10 07:32 UTC, stephdl commented
yes first remove, then print

2020-04-10 09:01 UTC, stephdl commented
@gsanchietti please could you review ?

2020-04-10 09:45 UTC, gsanchietti requested changes

2020-04-10 09:45 UTC, gsanchietti commented on createlinks
> +
Add missing license header.

2020-04-10 09:45 UTC, gsanchietti commented on createlinks
> +      R2W-OTP-enable
Please do not use events with with capital letters:
```suggestion
      nethserver-vpn-ui-save
```

2020-04-10 09:45 UTC, gsanchietti commented on root/etc/e-smith/events/actions/nethserver-vpn-ui-find-forced-users-to-otp
> +
Add missing license

2020-04-10 09:45 UTC, gsanchietti commented on root/etc/e-smith/events/actions/nethserver-vpn-ui-find-forced-users-to-otp
> +        close($FILE);
No need to write something inside the file, also do not die here (it prevents correct creation of next files):
```suggestion
   { open my $f, '>', "/var/lib/nethserver/openvpn-certificate-otp/$key" }
```

2020-04-10 09:45 UTC, gsanchietti commented on api/openvpn-rw/update
> +     system(("/sbin/e-smith/signal-event", "-j", "R2W-OTP-enable"));
```suggestion
     system(("/sbin/e-smith/signal-event", "-j", "nethserver-vpn-ui-save"));
```

2020-04-10 09:45 UTC, gsanchietti commented on api/openvpn-rw/update
> +     system(("/sbin/e-smith/signal-event", "-j", "R2W-OTP-enable"));
```suggestion
     system(("/sbin/e-smith/signal-event", "-j", "nethserver-vpn-ui-save"));
```

Also check if `success()` call is still needed.

2020-04-10 12:38 UTC, gsanchietti approved these changes

2020-04-10 14:02 UTC, merged