Improve management of connections table
NethServer/nethserver-vpn-ui pull request #38
Opened 2020-07-28 06:54 UTC by andre8244

Do not throw error if `connections` table does not exist

NethServer/dev#6242

2020-07-28 07:35 UTC, gsanchietti approved these changes

2020-07-30 08:02 UTC, gsanchietti requested changes

2020-07-30 08:02 UTC, gsanchietti commented on api/openvpn-rw/connection-history
> +    sys.exit(1)
Why not reuse the same logic of line 38 and writing to stderr? stederr will be already available inside the log.
```suggestion
if not database_exists:
    sys.stderr.write('Error: {} does not exist. Please execute /etc/e-smith/events/actions/nethserver-openvpn-create-connections-db'.format(DATABASE_PATH))
    sys.exit(1)
```

2020-07-30 08:02 UTC, gsanchietti commented on api/openvpn-rw/connection-history
> +import syslog
See suggestion below
```suggestion
```

2020-07-30 08:02 UTC, gsanchietti commented on api/openvpn-rw/connection-history-csv
> +    sys.exit(1)
Write directly to stderr, make sure that the caller script doesn't redirect stderr to /dev/null

2020-07-30 08:02 UTC, gsanchietti commented on api/openvpn-rw/top-traffic-accounts
> +    sys.exit(1)
Same as above, write to stderr

2020-07-30 08:39 UTC, gsanchietti approved these changes

2020-07-30 08:42 UTC, edospadoni approved these changes

2020-07-30 12:17 UTC, merged